version: 2
jobs:
 build:
   docker:
       - image: jetcipher/circleci-dotnet-core:3.0
   steps:
     - checkout
     - run:
         name: Restore
         command: dotnet restore
         working_directory: PasswordChecker
     - run:
         name: Build
         command: dotnet build -c Release
         working_directory: PasswordChecker
